# Generated by Django 3.2.9 on 2021-12-29 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_proveedoresmodel'),
        ('basededatos', '0006_auto_20211228_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_visits_report', models.CharField(max_length=350, verbose_name='Reporte de Visitas de Clientes')),
                ('commissions', models.CharField(max_length=50, verbose_name='Comisiones')),
                ('reference_guides', models.CharField(max_length=50, verbose_name='Guias de remisión')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_cliente', to='basededatos.clientmodel')),
                ('products', models.ManyToManyField(to='inventario.ProductModel')),
                ('services', models.ManyToManyField(to='inventario.ServiceModel')),
            ],
        ),
    ]
