# Generated by Django 3.2.9 on 2022-01-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('basededatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sales', models.CharField(choices=[('0', 'Servicios Generales (Obras)'), ('1', 'Productos y Servicios (Video Vigilancia)')], max_length=2, verbose_name='Tipo de venta')),
                ('contracts', models.ImageField(default=None, upload_to='contratos', verbose_name='Contrato Firmado')),
                ('address', models.CharField(max_length=20, verbose_name='Direccion')),
                ('type_method_products', models.CharField(blank=True, choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, null=True, verbose_name='Tipo pago producto')),
                ('down_payment_producto_cre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuota Inicial Productos')),
                ('quotas_producto_cre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cant. Cuotas Productos')),
                ('type_method_services', models.CharField(blank=True, choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, null=True, verbose_name='Tipo pago Servicio')),
                ('down_payment_servicios_cre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuota Inicial Servicio')),
                ('quotas_servicios_cre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cant. Cuotas Servicio')),
                ('bills_receivable', models.IntegerField(blank=True, null=True)),
                ('payment_notifications', models.BooleanField(default=False)),
                ('details', models.CharField(blank=True, max_length=350, null=True, verbose_name='Detalle')),
                ('descriptions', models.CharField(blank=True, max_length=350, null=True, verbose_name='Descripcion')),
                ('materials', models.CharField(blank=True, max_length=350, null=True, verbose_name='Materiales')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('quote', models.IntegerField(blank=True, null=True, verbose_name='Cotización')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_cliente', to='basededatos.clientmodel')),
                ('products', models.ManyToManyField(blank=True, to='inventario.ProductModel')),
                ('services', models.ManyToManyField(blank=True, to='inventario.ServiceModel')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
