# Generated by Django 3.2.9 on 2022-01-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_proveedoresmodel'),
        ('basededatos', '0010_monitoreomodel_type_sales'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasObrasModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts', models.CharField(max_length=20, verbose_name='Contratos')),
                ('address', models.CharField(max_length=20, unique=True, verbose_name='Direccion')),
                ('details', models.CharField(max_length=350, verbose_name='Detalle')),
                ('descriptions', models.CharField(max_length=350, verbose_name='Descripcion')),
                ('materials', models.CharField(max_length=350, verbose_name='Materiales')),
                ('cost', models.CharField(max_length=350, verbose_name='Costo')),
                ('Quote', models.CharField(max_length=350, verbose_name='Cotización')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_obras_cliente', to='basededatos.clientmodel')),
            ],
            options={
                'verbose_name_plural': 'Ventas Por Obras',
            },
        ),
        migrations.CreateModel(
            name='VentasVideoVigilanciaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts', models.CharField(max_length=20, verbose_name='Contratos')),
                ('address', models.CharField(max_length=20, unique=True, verbose_name='Direccion')),
                ('type_method_products', models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, verbose_name='Tipo pago producto')),
                ('down_payment_producto_cre', models.CharField(max_length=20, verbose_name='Cuota Inicial')),
                ('quotas_producto_cre', models.CharField(max_length=20, verbose_name='Cant. Cuotas')),
                ('type_method_services', models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, verbose_name='Tipo pago servicio')),
                ('down_payment_servicios_cre', models.CharField(max_length=20, verbose_name='Cuota Inicial')),
                ('quotas_servicios_cre', models.CharField(max_length=20, verbose_name='Cant. Cuotas')),
                ('bills_receivable', models.IntegerField()),
                ('payment_notifications', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreo_obras_cliente', to='basededatos.clientmodel')),
                ('products', models.ManyToManyField(to='inventario.ProductModel')),
                ('services', models.ManyToManyField(to='inventario.ServiceModel')),
            ],
            options={
                'verbose_name_plural': 'Ventas Por Video Vigilancia',
            },
        ),
        migrations.DeleteModel(
            name='VentasModelo',
        ),
    ]
