# Generated by Django 3.2.9 on 2022-01-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20220111_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasobrasmodelo',
            name='main_image',
            field=models.ImageField(default='', upload_to='ventas_obras_modelo', verbose_name='imagen principal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventasobrasmodelo',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='ventasvideovigilanciamodelo',
            name='down_payment_producto_cre',
            field=models.CharField(max_length=20, verbose_name='Cuota Inicial Productos'),
        ),
        migrations.AlterField(
            model_name='ventasvideovigilanciamodelo',
            name='down_payment_servicios_cre',
            field=models.CharField(max_length=20, verbose_name='Cuota Inicial Servicio'),
        ),
        migrations.AlterField(
            model_name='ventasvideovigilanciamodelo',
            name='quotas_producto_cre',
            field=models.CharField(max_length=20, verbose_name='Cant. Cuotas Productos'),
        ),
        migrations.AlterField(
            model_name='ventasvideovigilanciamodelo',
            name='quotas_servicios_cre',
            field=models.CharField(max_length=20, verbose_name='Cant. Cuotas Servicio'),
        ),
        migrations.AlterField(
            model_name='ventasvideovigilanciamodelo',
            name='type_method_services',
            field=models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, verbose_name='Tipo pago Servicio'),
        ),
    ]
