# Generated by Django 3.2.9 on 2022-01-11 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20220111_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventasmodelo',
            options={'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='ventasmodelo',
            name='type_sales',
            field=models.CharField(choices=[('0', 'Servicios Generales (Obras)'), ('1', 'Productos y Servicios (Video Vigilancia)')], default=django.utils.timezone.now, max_length=2, verbose_name='Tipo de venta'),
            preserve_default=False,
        ),
    ]
