# Generated by Django 3.2.9 on 2022-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_proveedoresmodel'),
        ('venta', '0005_auto_20220111_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='contracts',
            field=models.ImageField(default='', upload_to='contratos', verbose_name='Contrato Firmado'),
        ),
        migrations.AlterField(
            model_name='ventasmodelo',
            name='products',
            field=models.ManyToManyField(null=True, to='inventario.ProductModel'),
        ),
    ]
