# Generated by Django 3.2.9 on 2022-01-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_proveedoresmodel'),
        ('venta', '0006_auto_20220111_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='inventario.ProductModel'),
        ),
        migrations.AlterField(
            model_name='ventasmodelo',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='inventario.ServiceModel'),
        ),
    ]
