# Generated by Django 3.2.9 on 2022-01-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20220111_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='bills_receivable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
