# Generated by Django 3.2.9 on 2022-01-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_alter_ventasmodelo_bills_receivable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='address',
            field=models.CharField(max_length=20, verbose_name='Direccion'),
        ),
    ]
