# Generated by Django 3.2.9 on 2022-01-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_proveedoresmodel'),
        ('venta', '0010_alter_ventasmodelo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='products',
            field=models.ManyToManyField(blank=True, to='inventario.ProductModel'),
        ),
        migrations.AlterField(
            model_name='ventasmodelo',
            name='quote',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='ventasmodelo',
            name='services',
            field=models.ManyToManyField(blank=True, to='inventario.ServiceModel'),
        ),
    ]
