# Generated by Django 3.2.9 on 2022-01-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_auto_20220112_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo'),
        ),
    ]
