# Generated by Django 3.2.9 on 2022-01-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_alter_ventasmodelo_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='contracts',
            field=models.ImageField(blank=True, default='', upload_to='contratos', verbose_name='Contrato Firmado'),
        ),
    ]
