# Generated by Django 3.2.9 on 2022-01-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_alter_ventasmodelo_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmodelo',
            name='contracts',
            field=models.ImageField(default=None, upload_to='contratos', verbose_name='Contrato Firmado'),
        ),
    ]
