# Generated by Django 3.2.9 on 2021-11-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=20, unique=True)),
                ('address', models.CharField(help_text='Direccion', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(help_text='Documento', max_length=20, unique=True)),
                ('type_document', models.CharField(choices=[(0, 'DNI'), (1, 'RUC')], max_length=2, verbose_name='Tipo de documento')),
                ('cash_payment', models.BooleanField(default=False)),
                ('payment_to_credit', models.BooleanField(default=False)),
                ('bills_receivable', models.IntegerField()),
                ('payment_notifications', models.BooleanField(default=False)),
                ('type_method_products', models.CharField(choices=[(0, 'Contado'), (1, 'Credito')], max_length=2, verbose_name='Tipo pago producto')),
                ('type_method_services', models.CharField(choices=[(0, 'Contado'), (1, 'Credito')], max_length=2, verbose_name='Tipo pago servicio')),
                ('date_received', models.DateTimeField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_cliente', to='inventario.productmodel')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cliente', to='inventario.servicemodel')),
            ],
        ),
    ]
