# Generated by Django 3.2.9 on 2021-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='type_document',
            field=models.CharField(choices=[('0', 'DNI'), ('1', 'RUC')], max_length=2, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='type_method_products',
            field=models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, verbose_name='Tipo pago producto'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='type_method_services',
            field=models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, verbose_name='Tipo pago servicio'),
        ),
    ]
