# Generated by Django 3.2.9 on 2021-11-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0002_auto_20211110_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'verbose_name_plural': 'Clientes'},
        ),
    ]
