# Generated by Django 3.2.9 on 2021-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20211121_1131'),
        ('basededatos', '0003_alter_clientmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='products',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='products',
            field=models.ManyToManyField(to='inventario.ProductModel'),
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='services',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='services',
            field=models.ManyToManyField(to='inventario.ServiceModel'),
        ),
    ]
