# Generated by Django 3.2.9 on 2021-12-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0004_auto_20211121_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
