# Generated by Django 3.2.9 on 2021-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_proveedoresmodel'),
        ('basededatos', '0005_alter_clientmodel_date_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='bills_receivable',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='payment_notifications',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='payment_to_credit',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='products',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='services',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='type_method_products',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='type_method_services',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='address_main',
            field=models.CharField(default='', help_text='Direccion Principal', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientModelOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=20, unique=True)),
                ('address', models.CharField(help_text='Direccion', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(help_text='Documento', max_length=20, unique=True)),
                ('type_document', models.CharField(choices=[('0', 'DNI'), ('1', 'RUC')], max_length=2, verbose_name='Tipo de documento')),
                ('cash_payment', models.BooleanField(default=False)),
                ('payment_to_credit', models.BooleanField(default=False)),
                ('bills_receivable', models.IntegerField()),
                ('payment_notifications', models.BooleanField(default=False)),
                ('type_method_products', models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, verbose_name='Tipo pago producto')),
                ('type_method_services', models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], max_length=2, verbose_name='Tipo pago servicio')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='inventario.ProductModel')),
                ('services', models.ManyToManyField(to='inventario.ServiceModel')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
