# Generated by Django 3.2.9 on 2021-12-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0006_auto_20211228_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts', models.CharField(max_length=20, verbose_name='Contratos')),
                ('address', models.CharField(max_length=20, verbose_name='Direccion')),
                ('cash_payment', models.BooleanField(default=False)),
                ('payment_to_credit', models.BooleanField(default=False)),
                ('bills_receivable', models.IntegerField()),
                ('payment_notifications', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreo_cliente', to='basededatos.clientmodel')),
            ],
            options={
                'verbose_name_plural': 'Monitoreos',
            },
        ),
    ]
