# Generated by Django 3.2.9 on 2021-12-29 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_proveedoresmodel'),
        ('basededatos', '0007_monitoreomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodelold',
            name='bills_receivable',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='payment_notifications',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='payment_to_credit',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='products',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='services',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='type_method_products',
        ),
        migrations.RemoveField(
            model_name='clientmodelold',
            name='type_method_services',
        ),
        migrations.AddField(
            model_name='monitoreomodel',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoreomodel',
            name='products',
            field=models.ManyToManyField(to='inventario.ProductModel'),
        ),
        migrations.AddField(
            model_name='monitoreomodel',
            name='services',
            field=models.ManyToManyField(to='inventario.ServiceModel'),
        ),
        migrations.AddField(
            model_name='monitoreomodel',
            name='type_method_products',
            field=models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], default=django.utils.timezone.now, max_length=2, verbose_name='Tipo pago producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoreomodel',
            name='type_method_services',
            field=models.CharField(choices=[('0', 'Contado'), ('1', 'Credito')], default=django.utils.timezone.now, max_length=2, verbose_name='Tipo pago servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoreomodel',
            name='address',
            field=models.CharField(max_length=20, unique=True, verbose_name='Direccion'),
        ),
    ]
