# Generated by Django 3.2.9 on 2021-12-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0008_auto_20211229_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreomodel',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='monitoreomodel',
            name='payment_to_credit',
        ),
    ]
