# Generated by Django 3.2.9 on 2022-01-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0009_auto_20211229_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreomodel',
            name='type_sales',
            field=models.CharField(choices=[('0', 'Servicios Generales (Obras)'), ('1', 'Productos y Servicios (Video Vigilancia)')], default=1, max_length=2, verbose_name='Tipo de venta'),
            preserve_default=False,
        ),
    ]
