# Generated by Django 3.2.9 on 2022-01-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0010_monitoreomodel_type_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='profile',
            field=models.ImageField(default='', upload_to='profile', verbose_name='profile'),
            preserve_default=False,
        ),
    ]
