# Generated by Django 3.2.9 on 2022-01-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0011_clientmodel_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombres', max_length=20, unique=True)),
                ('address_main', models.CharField(help_text='Direccion', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_document', models.CharField(choices=[('0', 'DNI'), ('1', 'RUC')], max_length=2, verbose_name='Tipo de documento')),
                ('document', models.CharField(help_text='Documento', max_length=20, unique=True)),
                ('profile', models.ImageField(upload_to='profile', verbose_name='profile')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(help_text='Nombres', max_length=20, unique=True),
        ),
    ]
