# Generated by Django 3.2.9 on 2022-01-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0013_alter_clientmodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='profile',
            field=models.ImageField(default='https://cdn.quasar.dev/img/boy-avatar.png', upload_to='profile', verbose_name='profile'),
        ),
    ]
