# Generated by Django 3.2.9 on 2022-01-29 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type_invoice', models.CharField(choices=[('0', 'Factura'), ('1', 'Boleta')], max_length=2, verbose_name='Tipo de pedido')),
                ('codigo', models.CharField(help_text='Id de la factura o boleta', max_length=20)),
                ('date_received', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='ProveedoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Nombres', max_length=20, unique=True)),
                ('address_main', models.CharField(help_text='Direccion Principal', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_document', models.CharField(choices=[('0', 'DNI'), ('1', 'RUC')], max_length=2, verbose_name='Tipo de documento')),
                ('document', models.CharField(help_text='Documento', max_length=20, unique=True)),
                ('date_received', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Nombre del servicio', max_length=20, unique=True)),
                ('quantity', models.CharField(help_text='Cantidad', max_length=20)),
                ('term', models.CharField(help_text='Plazo', max_length=20)),
                ('quota', models.CharField(help_text='Cuota', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Activo')),
                ('date_received', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=20, unique=True)),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('code', models.CharField(max_length=20, verbose_name='Codigo de articulo')),
                ('date_of_entry', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('internal_product_code', models.CharField(max_length=100, verbose_name='Codigo interno de producto')),
                ('bar_code', models.CharField(max_length=100, verbose_name='Codigo de barra')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Numeros de Series')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Compra')),
                ('obervations', models.CharField(default='Sin observaciones', max_length=100, verbose_name='Observaciones')),
                ('tickets_purchases', models.CharField(max_length=12, verbose_name='Stock Minino')),
                ('outflows_sales', models.CharField(default=0, max_length=12, verbose_name='Ventas')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Venta')),
                ('description', models.CharField(default='Sin descripcion', max_length=100, verbose_name='Descripcion')),
                ('date_received', models.DateTimeField(verbose_name='Creado')),
                ('invoice_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_factura', to='inventario.facturamodel')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_producto', to='inventario.proveedoresmodel'),
        ),
    ]
