# Generated by Django 3.2.9 on 2021-11-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_invoice', models.CharField(choices=[(0, 'Factura'), (1, 'Boleta')], max_length=2, verbose_name='Tipo de documento')),
                ('codigo', models.CharField(help_text='Id de la factura o boleta', max_length=20)),
                ('date_received', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=20, unique=True)),
                ('date_received', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del servicio', max_length=20, unique=True)),
                ('date_received', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
