# Generated by Django 3.2.9 on 2021-11-21 16:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturamodel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='facturamodel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='bar_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='code',
            field=models.CharField(default=0, max_length=20, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='code_type',
            field=models.CharField(choices=[(0, 'Factura'), (1, 'Boleta'), (2, 'Guia de Remisión')], default=0, max_length=1, verbose_name='Tipo de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Costo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrada'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.CharField(default='test', max_length=100, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='internal_product_code',
            field=models.IntegerField(default='0001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='obervations',
            field=models.CharField(default='ninguna', max_length=100, verbose_name='Observaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='outflows_sales',
            field=models.CharField(default=0, max_length=12, verbose_name='Ventas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='plans',
            field=models.CharField(default='sin planes', max_length=20, verbose_name='Planers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_address',
            field=models.CharField(default='local', max_length=50, verbose_name='Direccion del producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Costo de Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='serial_number',
            field=models.IntegerField(default='00002'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tickets_purchases',
            field=models.CharField(default=0, max_length=12, verbose_name='Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='type_of_services',
            field=models.CharField(default='ninguno', max_length=20, verbose_name='Tipo de servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
