# Generated by Django 3.2.9 on 2022-01-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturamodel',
            name='codigo',
            field=models.CharField(help_text='Id de la factura o boleta', max_length=40),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Codigo de articulo'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='marca',
            field=models.CharField(max_length=40, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='modelo',
            field=models.CharField(max_length=40, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(help_text='Nombre del producto', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedoresmodel',
            name='address_main',
            field=models.CharField(help_text='Direccion Principal', max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedoresmodel',
            name='document',
            field=models.CharField(help_text='Documento', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedoresmodel',
            name='name',
            field=models.CharField(help_text='Nombres', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='name',
            field=models.CharField(help_text='Nombre del servicio', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='quantity',
            field=models.CharField(help_text='Cantidad', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='quota',
            field=models.CharField(help_text='Cuota', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='term',
            field=models.CharField(help_text='Plazo', max_length=40),
        ),
    ]
