# Generated by Django 3.2.9 on 2021-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20211121_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='code_type',
            field=models.CharField(choices=[(0, 'Factura'), (1, 'Boleta'), (2, 'Guia de Remisión')], default=0, max_length=1, verbose_name='Tipo de registro'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(default='Sin descripcion', max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='obervations',
            field=models.CharField(default='Sin observaciones', max_length=100, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='outflows_sales',
            field=models.CharField(default=0, max_length=12, verbose_name='Ventas'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='plans',
            field=models.CharField(default='Sin planes', max_length=20, verbose_name='Planes'),
        ),
    ]
