# Generated by Django 3.2.9 on 2022-01-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20220130_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='date_received',
        ),
    ]
