# Generated by Django 3.2.9 on 2022-01-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_productmodel_date_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturamodel',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='proveedoresmodel',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='date_received',
        ),
    ]
