# Generated by Django 3.2.9 on 2021-12-29 03:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_productmodel_code_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type_invoice', models.CharField(choices=[(0, 'Factura'), (1, 'Boleta')], max_length=2, verbose_name='Tipo de documento')),
                ('codigo', models.CharField(help_text='Id de la factura o boleta', max_length=20)),
                ('date_received', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
