# Generated by Django 3.2.9 on 2022-01-25 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20220120_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='active',
            field=models.BooleanField(default=True, help_text='Activo'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='quantity',
            field=models.CharField(default=django.utils.timezone.now, help_text='Cantidad', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='quota',
            field=models.CharField(default=django.utils.timezone.now, help_text='Cuota', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='term',
            field=models.CharField(default=django.utils.timezone.now, help_text='Plazo', max_length=20),
            preserve_default=False,
        ),
    ]
