# Generated by Django 3.2.9 on 2022-01-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20220124_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedoresmodel',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='proveedoresmodel',
            name='type_invoice',
        ),
        migrations.AddField(
            model_name='proveedoresmodel',
            name='address_main',
            field=models.CharField(default='', help_text='Direccion Principal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedoresmodel',
            name='document',
            field=models.CharField(default=0, help_text='Documento', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedoresmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedoresmodel',
            name='name',
            field=models.CharField(default='', help_text='Nombres', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedoresmodel',
            name='type_document',
            field=models.CharField(choices=[('0', 'DNI'), ('1', 'RUC')], default=1, max_length=2, verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
    ]
