# Generated by Django 3.2.9 on 2022-01-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20220124_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturamodel',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factura_producto', to='inventario.proveedoresmodel'),
            preserve_default=False,
        ),
    ]
