# Generated by Django 3.2.9 on 2022-01-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_facturamodel_type_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturamodel',
            name='type_invoice',
            field=models.CharField(choices=[('0', 'Factura'), ('1', 'Boleta')], max_length=2, verbose_name='Tipo de pedido'),
        ),
    ]
