# Generated by Django 3.2.9 on 2022-01-25 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_facturamodel_type_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='invoice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='producto_factura', to='inventario.facturamodel'),
            preserve_default=False,
        ),
    ]
