# Generated by Django 3.2.9 on 2022-01-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_productmodel_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='invoice',
            new_name='invoice_relation',
        ),
    ]
