# Generated by Django 3.2.9 on 2022-01-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_rename_invoice_productmodel_invoice_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='bar_code',
            field=models.CharField(max_length=100, verbose_name='Codigo de barra'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='internal_product_code',
            field=models.CharField(max_length=100, verbose_name='Codigo interno de producto'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='Numeros de Series'),
        ),
    ]
