# Generated by Django 3.2.9 on 2022-01-29 05:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='Nombres')),
                ('lastnames', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=50, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=12, verbose_name='DNI')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('contracts', models.CharField(max_length=20, verbose_name='Contratos')),
            ],
            options={
                'verbose_name': 'Personal',
            },
        ),
    ]
