# Generated by Django 3.2.9 on 2021-11-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionhumana', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalmodel',
            options={'verbose_name': 'Personal'},
        ),
    ]
