# Generated by Django 3.2.9 on 2021-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionhumana', '0002_alter_personalmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmodel',
            name='dni',
            field=models.CharField(max_length=12, verbose_name='DNI'),
        ),
    ]
